# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7c30514aeee118faa758fb3a01a8a9a65c385bf53422bb81cf1613cb841d0850f53cee418918a5311d92e85390a93a3525d0fcd43e09552aa65d9e3dd400e5

test:
  secret_key_base: 097612b42368570095227f58044a15ef55612c5ab2efec9da5936a88e658db564fa941fb318586c2b89fbe87167dcf8d4e7ad39e23be7e5e125eb7a6d21e0b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
